### ISSUE TITLE
Update helm chart to work with an ingress with multiple paths

### ISSUE THREAD

**Issue by jesty** [Activiti/activiti-cloud-common-chart#8]
Configure an ingress with multiple paths that refer to a single service.
To configure this ingress we still use the ingress.path property in values.yml as context path, and we defined new array property, ingress.subPaths, with all paths referring to the service:

```
ingress:
  path: /{{ .Release.Name }}
  subPaths:
    - "/query"
    - "/notifications"
    - "/audit"
  enabled: true
```
